import { invoke } from '@tauri-apps/api/core';
import type { AppConfig, DanmakuStatus, DebugSongRequestResult, HotkeyStatus, OBSOverlayStatus, RebuildReport, SearchResult, SongInfo, SongRequest } from '../types';

export const api = {
  getConfig: () => invoke<AppConfig>('get_config'),
  saveConfig: (config: AppConfig, skipValidation?: boolean) => invoke<void>('save_config', { config, skipValidation: skipValidation ?? false }),
  getAllSongs: () => invoke<SongInfo[]>('get_all_songs'),
  reloadDatabase: () => invoke<number>('reload_database'),
  rebuildDatabase: () => invoke<RebuildReport>('rebuild_database'),
  searchSongs: (query: string, difficulty?: number | null, difficultyKey?: string | null) =>
    invoke<SearchResult[]>('search_songs', {
      query,
      difficulty: difficulty ?? null,
      difficultyKey: difficultyKey ?? null,
    }),
  debugSongRequest: (text: string) => invoke<DebugSongRequestResult>('debug_song_request', { text }),
  debugEnqueueSong: (text: string) => invoke<DebugSongRequestResult>('debug_enqueue_song', { text }),
  getQueue: () => invoke<SongRequest[]>('get_queue'),
  getHistory: () => invoke<SongRequest[]>('get_queue_history'),
  removeFromQueue: (songId: number) => invoke<boolean>('remove_from_queue', { songId }),
  clearQueue: () => invoke<void>('clear_queue'),
  nextSong: () => invoke<SongRequest | null>('next_song'),
  changeSong: (songId: number, difficultyTier: string) => invoke<string>('change_song', { songId, difficultyTier }),
  reconnectGame: () => invoke<boolean>('reconnect_game'),
  getGameConnectionStatus: () => invoke<boolean>('get_game_connection_status'),
  startDanmaku: (roomId: number) => invoke<void>('start_danmaku', { roomId }),
  stopDanmaku: () => invoke<void>('stop_danmaku'),
  getDanmakuStatus: () => invoke<DanmakuStatus>('get_danmaku_status'),
  registerHotkey: () => invoke<HotkeyStatus>('register_hotkey'),
  unregisterHotkey: () => invoke<HotkeyStatus>('unregister_hotkey'),
  getHotkeyStatus: () => invoke<HotkeyStatus>('get_hotkey_status'),
  startObsOverlay: () => invoke<OBSOverlayStatus>('start_obs_overlay'),
  stopObsOverlay: () => invoke<OBSOverlayStatus>('stop_obs_overlay'),
  getObsOverlayStatus: () => invoke<OBSOverlayStatus>('get_obs_overlay_status'),
  isFirstRun: () => invoke<boolean>('is_first_run'),
};

export const emptyConfig: AppConfig = {
  room_id: 0,
  hotkey: 'ctrl+shift+n',
  data_dir: 'Data',
  mods_dir: '',
  auto_play_next: false,
  auto_play_interval: 300,
  max_queue_size: 50,
  allow_duplicates: false,
  obs_overlay_enabled: true,
  obs_overlay_host: '127.0.0.1',
  obs_overlay_port: 8765,
  obs_overlay_title: '点歌队列',
  song_command_prefix: '点歌',
  sessdata: '',
  fetch_chinese_names: false,
  http_proxy: '',
  default_search_difficulty: 'extreme',
  difficulty_tolerance: 0.5,
  difficulty_fallback: 'easier',
  llm_enabled: false,
  llm_api_key: '',
  llm_base_url: 'https://api.deepseek.com',
  llm_model: 'deepseek-chat',
  llm_max_tokens: 150,
  config_file: 'config.json',
};
